### ISSUE TITLE
Privacy Policies

### ISSUE THREAD

**Issue by rmiklautz** [FreeRDP/freerdp.github.io#1]
For the GooglePlay Store we must provide a link to our privacy policies even if we do not collect any data!

However, Google recommends to answer following privacy policy questions:
Link: https://developers.google.com/actions/distribute/privacy-policy-guide

 **What information do you collect?**

In your policy you should disclose all the information your Action collects. This includes information that you may collect automatically, such as server and HTTP logs, data transmitted by the Actions on Google API to you, and usage information. This also includes information that you get from the user, either directly or via the permissions API. You should also disclose whether you collect any persistent identifiers (like the Google ID).

 **How do you use the information?**

 In your policy, you should disclose how you use the information you collect. For example, you may use the information to provide certains services to users, to recognize them the next time they use your Action, or to send them promotional emails.

**What information do you share?**

In your policy, you should disclose the circumstances when you share information. For example, you may share information with third parties as part of the service (like a restaurant reservation Action), with other users (like a social network or forum), with marketing partners, or with service providers that assist with your service (like hosting companies or technology platforms).

**Comment by bmiklautz** [comment]
@rmiklautz just to clarify we do need that for aFreeRDP, right?

**Comment by rmiklautz** [comment]
Yes,  privacy policy is only needed for aFreeRDP resp. Google Play Store!
